services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: anonymous_email_db
    environment:
      POSTGRES_DB: anonymous_email
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/02-init-db.sh
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d anonymous_email"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (Rate Limiting용)
  redis:
    image: redis:7-alpine
    container_name: anonymous_email_redis
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: unless-stopped

  # Node.js 애플리케이션
  app:
    build: .
    container_name: anonymous_email_app
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: anonymous_email
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  # Nginx (리버스 프록시)
  nginx:
    image: nginx:alpine
    container_name: anonymous_email_nginx
    ports:
      - "80:80"
      - "443:443"
      - "2525:2525"  # SMTP 프록시 포트 (외부)
      - "10001:10001"  # SMTP 서버 포트 (내부)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
