services:
  - type: web
    name: anonymous-email-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8081
      - key: DOMAIN
        value: nosignup.kr
      - key: EMAIL_DOMAIN
        value: nosignup.kr
